language: ruby
script: bundle exec middleman build

env:
  global:
    - GIT_COMMITTER_NAME=willnet
    - GIT_COMMITTER_EMAIL=netwillnet@gmail.com
    - GIT_AUTHOR_NAME=willnet
    - GIT_AUTHOR_EMAIL=netwillnet@gmail.com
    - secure: "QNZtTUtaOy00i8hH41wmfnzvTgA+219Ny1VMNDlVdSuOidxEyikUA+c+qz0urzTZqaLpcC6SUGQ6zH7bD2SemvzWUA/B32FaKF46k7scHzIx+vcoAbigDxrglLKda3ksLOt/vtlR0NpWasocPY4ohmPkJGwgy6uFQbTE/ZPsIEw="
    
before_script:
  - git clone --quiet https://github.com/ginzarb/ginzarb.github.io.git build
  - pushd build
  - git checkout -b master
  - popd

after_success:
  - cd build
  - git add -A
  - git commit -m 'Reflect changed sources'
  - '[ "$TRAVIS_BRANCH" == "source" ] && [ $GH_TOKEN ] && git push -f --quiet https://$GH_TOKEN@github.com/ginzarb/ginzarb.github.io.git master 2> /dev/null'
