language: ruby
script: bundle exec middleman build

env:
  global:
    - GIT_COMMITTER_NAME=willnet
    - GIT_COMMITTER_EMAIL=netwillnet@gmail.com
    - GIT_AUTHOR_NAME=willnet
    - GIT_AUTHOR_EMAIL=netwillnet@gmail.com
    - secure: "CjL+7wyaWy9+5/z+9dPtHHI4Ni7Kr3RQyIg2nyZZBChdXX+g8iwgV7prrE3vbIEnjgG4bv9yedV2FlX9OlJNK1Vv0ssdzl2dymHC2sN2zNjQMlbkx1hI3OQrUgjD6Fi2yY/Y/bfqDRH2UGEMzaRpVtUmsM1ppQQmDvT6ZmG2GPI="
    
before_script:
  - git clone --quiet https://github.com/ginzarb/ginzarb.github.io.git build
  - pushd build
  - git checkout -b master
  - popd

after_success:
  - cd build
  - git add -A
  - git commit -m 'Reflect changed sources'
  - '[ "$TRAVIS_BRANCH" == "source" ] && [ $GH_TOKEN ] && git push -f https://$GH_TOKEN@github.com/ginzarb.github.io.git master