name: Build and Deploy

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3

    - name: Install dependencies
      run: bundle install

    - name: Build with Middleman
      run: bundle exec middleman build

    - name: Deploy
      if: github.ref == 'refs/heads/source'
      run: |
        cd build
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout -b master
        git add -A
        git commit -m 'Reflect changed sources'
        git push